"""Migrations must produce the same schema the models declare.

Two real bugs were caught here during Phase 3: custom column types
(`StrEnumType`, the JSON/JSONB variant) rendered into autogenerated revisions in
a form that could not execute. A migration that fails only on a fresh database
is the worst kind, because development databases are usually not fresh.
"""

from __future__ import annotations

import asyncio
from pathlib import Path

import pytest
from alembic.config import Config
from alembic.script import ScriptDirectory
from sqlalchemy import inspect
from sqlalchemy.ext.asyncio import create_async_engine

from app.db.base import Base

BACKEND_ROOT = Path(__file__).resolve().parents[1]
ALEMBIC_INI = BACKEND_ROOT / "alembic.ini"


def _alembic_config(database_url: str) -> Config:
    config = Config(str(ALEMBIC_INI))
    config.set_main_option("script_location", str(BACKEND_ROOT / "alembic"))
    config.set_main_option("sqlalchemy.url", database_url)
    return config


class TestMigrations:
    def test_there_is_exactly_one_head(self):
        """Two heads mean two phases branched and nobody merged them."""
        script = ScriptDirectory.from_config(_alembic_config("sqlite://"))
        assert len(script.get_heads()) == 1

    def test_every_revision_is_reachable_from_head(self):
        script = ScriptDirectory.from_config(_alembic_config("sqlite://"))
        head = script.get_current_head()
        reachable = {rev.revision for rev in script.walk_revisions("base", head)}
        on_disk = {rev.revision for rev in script.walk_revisions()}
        assert on_disk == reachable

    def test_migrations_build_the_schema_the_models_declare(self, tmp_path):
        """Run every migration on an empty database and compare table columns."""
        from alembic import command

        db_path = tmp_path / "migrated.db"
        # env.py drives migrations through an async engine, so the URL must
        # name an async driver even for a throwaway file.
        config = _alembic_config(f"sqlite+aiosqlite:///{db_path.as_posix()}")
        command.upgrade(config, "head")

        async def read_schema() -> dict[str, set[str]]:
            engine = create_async_engine(f"sqlite+aiosqlite:///{db_path.as_posix()}")
            async with engine.connect() as conn:
                tables = await conn.run_sync(lambda sync: set(inspect(sync).get_table_names()))
                columns = {}
                for table in tables:
                    columns[table] = await conn.run_sync(
                        lambda sync, t=table: {col["name"] for col in inspect(sync).get_columns(t)}
                    )
            await engine.dispose()
            return columns

        migrated = asyncio.run(read_schema())
        migrated.pop("alembic_version", None)

        declared = {
            table.name: {column.name for column in table.columns}
            for table in Base.metadata.sorted_tables
        }

        assert set(migrated) == set(declared), "migrations and models disagree on tables"
        for table, expected_columns in declared.items():
            assert migrated[table] == expected_columns, f"column mismatch on {table}"

    @pytest.mark.parametrize(
        "table",
        ["users", "refresh_tokens", "audit_logs", "login_attempts"],
    )
    def test_phase_3_tables_are_declared(self, table):
        assert table in Base.metadata.tables
