"""p08 reverse matching routes and notifications

Revision ID: 0b82cec227ef
Revises: d898443c3fd4
Create Date: 2026-08-19 10:43:16.004310
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import app.db.types  # noqa: F401  # custom column types used by autogenerate
import app.db.types
import sqlalchemy as sa
revision: str = '0b82cec227ef'
down_revision: str | None = 'd898443c3fd4'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('user_id', app.db.types.GUID(), nullable=True),
    sa.Column('role_target', sa.String(length=48), nullable=True),
    sa.Column('category', sa.String(length=48), nullable=False),
    sa.Column('severity', sa.String(length=48), nullable=False),
    sa.Column('title', sa.String(length=240), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('entity_type', sa.String(length=64), nullable=True),
    sa.Column('entity_id', app.db.types.GUID(), nullable=True),
    sa.Column('action_url', sa.String(length=255), nullable=True),
    sa.Column('payload', app.db.types.JSONType, nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', app.db.types.UTCDateTime(), nullable=True),
    sa.Column('dedupe_key', sa.String(length=160), nullable=False),
    sa.Column('created_at', app.db.types.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.db.types.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notifications_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications')),
    sa.UniqueConstraint('dedupe_key', name=op.f('uq_notifications_dedupe_key'))
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index('ix_notifications_inbox', ['user_id', 'is_read', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_is_read'), ['is_read'], unique=False)
        batch_op.create_index('ix_notifications_role_inbox', ['role_target', 'is_read', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_role_target'), ['role_target'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_severity'), ['severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('route_type', sa.String(length=24), nullable=True))
        batch_op.add_column(sa.Column('route_label', sa.String(length=240), nullable=True))
        batch_op.add_column(sa.Column('route_account_id', app.db.types.GUID(), nullable=True))
        batch_op.add_column(sa.Column('reachability', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('priority_score', sa.Numeric(precision=5, scale=2), nullable=True))
        batch_op.create_index(batch_op.f('ix_matches_priority_score'), ['priority_score'], unique=False)
        batch_op.create_index('ix_matches_reverse_rank', ['resource_id', 'direction', 'priority_score'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_matches_route_account_id_accounts'), 'accounts', ['route_account_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_matches_route_account_id_accounts'), type_='foreignkey')
        batch_op.drop_index('ix_matches_reverse_rank')
        batch_op.drop_index(batch_op.f('ix_matches_priority_score'))
        batch_op.drop_column('priority_score')
        batch_op.drop_column('reachability')
        batch_op.drop_column('route_account_id')
        batch_op.drop_column('route_label')
        batch_op.drop_column('route_type')

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_user_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_severity'))
        batch_op.drop_index(batch_op.f('ix_notifications_role_target'))
        batch_op.drop_index('ix_notifications_role_inbox')
        batch_op.drop_index(batch_op.f('ix_notifications_is_read'))
        batch_op.drop_index('ix_notifications_inbox')
        batch_op.drop_index(batch_op.f('ix_notifications_entity_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_created_at'))
        batch_op.drop_index(batch_op.f('ix_notifications_category'))

    op.drop_table('notifications')
    # ### end Alembic commands ###
