"""p12 excel import staging

Revision ID: 1092763ab2a1
Revises: 7c78e52b08ef
Create Date: 2026-08-19 16:27:46.706331
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import app.db.types  # noqa: F401  # custom column types used by autogenerate
import app.db.types
import sqlalchemy as sa
revision: str = '1092763ab2a1'
down_revision: str | None = '7c78e52b08ef'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('import_batches',
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('entity_type', sa.String(length=48), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('document_id', app.db.types.GUID(), nullable=True),
    sa.Column('status', sa.String(length=48), nullable=False),
    sa.Column('total_rows', sa.Integer(), nullable=False),
    sa.Column('valid_rows', sa.Integer(), nullable=False),
    sa.Column('invalid_rows', sa.Integer(), nullable=False),
    sa.Column('duplicate_rows', sa.Integer(), nullable=False),
    sa.Column('warning_rows', sa.Integer(), nullable=False),
    sa.Column('committed_rows', sa.Integer(), nullable=False),
    sa.Column('file_errors', app.db.types.JSONType, nullable=True),
    sa.Column('created_by', app.db.types.GUID(), nullable=True),
    sa.Column('committed_at', app.db.types.UTCDateTime(), nullable=True),
    sa.Column('committed_by', app.db.types.GUID(), nullable=True),
    sa.Column('created_at', app.db.types.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.db.types.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['committed_by'], ['users.id'], name=op.f('fk_import_batches_committed_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_import_batches_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_import_batches_document_id_documents'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_import_batches'))
    )
    with op.batch_alter_table('import_batches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_import_batches_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_import_batches_created_by'), ['created_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_import_batches_entity_type'), ['entity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_import_batches_status'), ['status'], unique=False)
        batch_op.create_index('ix_import_batches_status_created', ['status', 'created_at'], unique=False)

    op.create_table('import_rows',
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('batch_id', app.db.types.GUID(), nullable=False),
    sa.Column('row_number', sa.Integer(), nullable=False),
    sa.Column('raw', app.db.types.JSONType, nullable=True),
    sa.Column('normalized', app.db.types.JSONType, nullable=True),
    sa.Column('validation_state', sa.String(length=48), nullable=False),
    sa.Column('errors', app.db.types.JSONType, nullable=True),
    sa.Column('warnings', app.db.types.JSONType, nullable=True),
    sa.Column('created_entity_id', app.db.types.GUID(), nullable=True),
    sa.Column('duplicate_of_id', app.db.types.GUID(), nullable=True),
    sa.Column('created_at', app.db.types.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.db.types.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['import_batches.id'], name=op.f('fk_import_rows_batch_id_import_batches'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_import_rows')),
    sa.UniqueConstraint('batch_id', 'row_number', name='import_row_unique')
    )
    with op.batch_alter_table('import_rows', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_import_rows_batch_id'), ['batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_import_rows_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_import_rows_state', ['batch_id', 'validation_state'], unique=False)
        batch_op.create_index(batch_op.f('ix_import_rows_validation_state'), ['validation_state'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('import_rows', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_import_rows_validation_state'))
        batch_op.drop_index('ix_import_rows_state')
        batch_op.drop_index(batch_op.f('ix_import_rows_created_at'))
        batch_op.drop_index(batch_op.f('ix_import_rows_batch_id'))

    op.drop_table('import_rows')
    with op.batch_alter_table('import_batches', schema=None) as batch_op:
        batch_op.drop_index('ix_import_batches_status_created')
        batch_op.drop_index(batch_op.f('ix_import_batches_status'))
        batch_op.drop_index(batch_op.f('ix_import_batches_entity_type'))
        batch_op.drop_index(batch_op.f('ix_import_batches_created_by'))
        batch_op.drop_index(batch_op.f('ix_import_batches_created_at'))

    op.drop_table('import_batches')
    # ### end Alembic commands ###
