"""p06 talent cloud documents and cv parsing

Revision ID: 30f9fc902d8e
Revises: fb9ad09a68d9
Create Date: 2026-08-18 16:03:07.752355
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import app.db.types  # noqa: F401  # custom column types used by autogenerate
import app.db.types
import sqlalchemy as sa
revision: str = '30f9fc902d8e'
down_revision: str | None = 'fb9ad09a68d9'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('storage_key', sa.String(length=255), nullable=False),
    sa.Column('storage_backend', sa.String(length=16), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=120), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=False),
    sa.Column('uploaded_by', app.db.types.GUID(), nullable=True),
    sa.Column('created_at', app.db.types.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.db.types.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], name=op.f('fk_documents_uploaded_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_documents')),
    sa.UniqueConstraint('storage_key', name=op.f('uq_documents_storage_key'))
    )
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documents_checksum_sha256'), ['checksum_sha256'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_created_at'), ['created_at'], unique=False)

    op.create_table('resources',
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=True),
    sa.Column('full_name', sa.String(length=160), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=48), nullable=True),
    sa.Column('resource_type', sa.String(length=48), nullable=False),
    sa.Column('headline', sa.String(length=240), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('total_experience_years', sa.Float(), nullable=True),
    sa.Column('relevant_experience_years', sa.Float(), nullable=True),
    sa.Column('current_location_country', sa.String(length=2), nullable=True),
    sa.Column('current_location_city', sa.String(length=120), nullable=True),
    sa.Column('willing_to_relocate', sa.Boolean(), nullable=False),
    sa.Column('nationality', sa.String(length=64), nullable=True),
    sa.Column('visa_status', sa.String(length=48), nullable=False),
    sa.Column('visa_country', sa.String(length=2), nullable=True),
    sa.Column('availability_status', sa.String(length=48), nullable=False),
    sa.Column('available_from', sa.Date(), nullable=True),
    sa.Column('notice_period_days', sa.Integer(), nullable=False),
    sa.Column('expected_cost_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('expected_cost_currency', sa.String(length=3), nullable=True),
    sa.Column('expected_cost_unit', sa.String(length=16), nullable=True),
    sa.Column('target_billing_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('target_billing_currency', sa.String(length=3), nullable=True),
    sa.Column('target_billing_unit', sa.String(length=16), nullable=True),
    sa.Column('assessment_status', sa.String(length=48), nullable=False),
    sa.Column('assessment_score', sa.Integer(), nullable=True),
    sa.Column('assessment_notes', sa.Text(), nullable=True),
    sa.Column('partner_account_id', app.db.types.GUID(), nullable=True),
    sa.Column('owner_id', app.db.types.GUID(), nullable=True),
    sa.Column('source', sa.String(length=24), nullable=False),
    sa.Column('review_status', sa.String(length=24), nullable=False),
    sa.Column('parsed_payload', app.db.types.JSONType, nullable=True),
    sa.Column('parse_confidence', sa.Float(), nullable=True),
    sa.Column('parse_model', sa.String(length=80), nullable=True),
    sa.Column('parsed_at', app.db.types.UTCDateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', app.db.types.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.db.types.UTCDateTime(), nullable=False),
    sa.Column('deleted_at', app.db.types.UTCDateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_resources_owner_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['partner_account_id'], ['accounts.id'], name=op.f('fk_resources_partner_account_id_accounts'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_resources'))
    )
    with op.batch_alter_table('resources', schema=None) as batch_op:
        batch_op.create_index('ix_resources_availability', ['availability_status', 'available_from'], unique=False)
        batch_op.create_index(batch_op.f('ix_resources_availability_status'), ['availability_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_resources_available_from'), ['available_from'], unique=False)
        batch_op.create_index(batch_op.f('ix_resources_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_resources_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_resources_current_location_country'), ['current_location_country'], unique=False)
        batch_op.create_index(batch_op.f('ix_resources_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_resources_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_resources_full_name'), ['full_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_resources_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_resources_partner_account_id'), ['partner_account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_resources_phone'), ['phone'], unique=False)
        batch_op.create_index(batch_op.f('ix_resources_resource_type'), ['resource_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_resources_review_status'), ['review_status'], unique=False)
        batch_op.create_index('ix_resources_type_active', ['resource_type', 'deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_resources_visa_status'), ['visa_status'], unique=False)

    op.create_table('resource_certifications',
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('resource_id', app.db.types.GUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('issuer', sa.String(length=160), nullable=True),
    sa.Column('issued_at', sa.Date(), nullable=True),
    sa.Column('expires_at', sa.Date(), nullable=True),
    sa.Column('credential_id', sa.String(length=120), nullable=True),
    sa.Column('created_at', app.db.types.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.db.types.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], name=op.f('fk_resource_certifications_resource_id_resources'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_resource_certifications'))
    )
    with op.batch_alter_table('resource_certifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_resource_certifications_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_resource_certifications_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_resource_certifications_resource_id'), ['resource_id'], unique=False)

    op.create_table('resource_documents',
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('resource_id', app.db.types.GUID(), nullable=False),
    sa.Column('document_id', app.db.types.GUID(), nullable=False),
    sa.Column('doc_type', sa.String(length=48), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('issue_date', sa.Date(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('issuing_country', sa.String(length=2), nullable=True),
    sa.Column('reference_number', sa.String(length=120), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', app.db.types.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.db.types.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_resource_documents_document_id_documents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], name=op.f('fk_resource_documents_resource_id_resources'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_resource_documents'))
    )
    with op.batch_alter_table('resource_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_resource_documents_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_resource_documents_doc_type'), ['doc_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_resource_documents_document_id'), ['document_id'], unique=False)
        batch_op.create_index('ix_resource_documents_expiry', ['expiry_date', 'doc_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_resource_documents_expiry_date'), ['expiry_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_resource_documents_resource_id'), ['resource_id'], unique=False)
        batch_op.create_index('ix_resource_documents_type', ['resource_id', 'doc_type'], unique=False)

    op.create_table('resource_experience',
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('resource_id', app.db.types.GUID(), nullable=False),
    sa.Column('company', sa.String(length=200), nullable=True),
    sa.Column('project_name', sa.String(length=200), nullable=True),
    sa.Column('role', sa.String(length=160), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('location', sa.String(length=160), nullable=True),
    sa.Column('technologies', app.db.types.JSONType, nullable=True),
    sa.Column('created_at', app.db.types.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.db.types.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], name=op.f('fk_resource_experience_resource_id_resources'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_resource_experience'))
    )
    with op.batch_alter_table('resource_experience', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_resource_experience_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_resource_experience_order', ['resource_id', 'start_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_resource_experience_resource_id'), ['resource_id'], unique=False)

    op.create_table('resource_skills',
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('resource_id', app.db.types.GUID(), nullable=False),
    sa.Column('skill_id', app.db.types.GUID(), nullable=False),
    sa.Column('years', sa.Float(), nullable=True),
    sa.Column('proficiency', sa.String(length=48), nullable=False),
    sa.Column('last_used_year', sa.Integer(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('created_at', app.db.types.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.db.types.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], name=op.f('fk_resource_skills_resource_id_resources'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], name=op.f('fk_resource_skills_skill_id_skills'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_resource_skills')),
    sa.UniqueConstraint('resource_id', 'skill_id', name='resource_skill_unique')
    )
    with op.batch_alter_table('resource_skills', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_resource_skills_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_resource_skills_resource_id'), ['resource_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_resource_skills_skill_id'), ['skill_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resource_skills', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_resource_skills_skill_id'))
        batch_op.drop_index(batch_op.f('ix_resource_skills_resource_id'))
        batch_op.drop_index(batch_op.f('ix_resource_skills_created_at'))

    op.drop_table('resource_skills')
    with op.batch_alter_table('resource_experience', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_resource_experience_resource_id'))
        batch_op.drop_index('ix_resource_experience_order')
        batch_op.drop_index(batch_op.f('ix_resource_experience_created_at'))

    op.drop_table('resource_experience')
    with op.batch_alter_table('resource_documents', schema=None) as batch_op:
        batch_op.drop_index('ix_resource_documents_type')
        batch_op.drop_index(batch_op.f('ix_resource_documents_resource_id'))
        batch_op.drop_index(batch_op.f('ix_resource_documents_expiry_date'))
        batch_op.drop_index('ix_resource_documents_expiry')
        batch_op.drop_index(batch_op.f('ix_resource_documents_document_id'))
        batch_op.drop_index(batch_op.f('ix_resource_documents_doc_type'))
        batch_op.drop_index(batch_op.f('ix_resource_documents_created_at'))

    op.drop_table('resource_documents')
    with op.batch_alter_table('resource_certifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_resource_certifications_resource_id'))
        batch_op.drop_index(batch_op.f('ix_resource_certifications_expires_at'))
        batch_op.drop_index(batch_op.f('ix_resource_certifications_created_at'))

    op.drop_table('resource_certifications')
    with op.batch_alter_table('resources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_resources_visa_status'))
        batch_op.drop_index('ix_resources_type_active')
        batch_op.drop_index(batch_op.f('ix_resources_review_status'))
        batch_op.drop_index(batch_op.f('ix_resources_resource_type'))
        batch_op.drop_index(batch_op.f('ix_resources_phone'))
        batch_op.drop_index(batch_op.f('ix_resources_partner_account_id'))
        batch_op.drop_index(batch_op.f('ix_resources_owner_id'))
        batch_op.drop_index(batch_op.f('ix_resources_full_name'))
        batch_op.drop_index(batch_op.f('ix_resources_email'))
        batch_op.drop_index(batch_op.f('ix_resources_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_resources_current_location_country'))
        batch_op.drop_index(batch_op.f('ix_resources_created_at'))
        batch_op.drop_index(batch_op.f('ix_resources_code'))
        batch_op.drop_index(batch_op.f('ix_resources_available_from'))
        batch_op.drop_index(batch_op.f('ix_resources_availability_status'))
        batch_op.drop_index('ix_resources_availability')

    op.drop_table('resources')
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_created_at'))
        batch_op.drop_index(batch_op.f('ix_documents_checksum_sha256'))

    op.drop_table('documents')
    # ### end Alembic commands ###
