"""individual job feed

Revision ID: 3f05caaa1d12
Revises: 1092763ab2a1
Create Date: 2026-10-01 12:57:25.465111
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import app.db.types  # noqa: F401  # custom column types used by autogenerate
import sqlalchemy as sa
revision: str = '3f05caaa1d12'
down_revision: str | None = '1092763ab2a1'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_postings',
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=240), nullable=False),
    sa.Column('company_name', sa.String(length=200), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('workplace_type', sa.String(length=48), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('url', sa.String(length=1000), nullable=True),
    sa.Column('source', sa.String(length=48), nullable=False),
    sa.Column('source_name', sa.String(length=64), nullable=True),
    sa.Column('posted_at', sa.Date(), nullable=True),
    sa.Column('raw_excerpt', sa.Text(), nullable=True),
    sa.Column('created_at', app.db.types.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.db.types.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_postings'))
    )
    with op.batch_alter_table('job_postings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_postings_company_name'), ['company_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_postings_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_postings_fingerprint'), ['fingerprint'], unique=True)
        batch_op.create_index(batch_op.f('ix_job_postings_source'), ['source'], unique=False)
        batch_op.create_index('ix_job_postings_workplace_posted', ['workplace_type', 'posted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_postings_workplace_type'), ['workplace_type'], unique=False)

    op.create_table('job_feed_items',
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('user_id', app.db.types.GUID(), nullable=False),
    sa.Column('posting_id', app.db.types.GUID(), nullable=False),
    sa.Column('received_at', app.db.types.UTCDateTime(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('is_saved', sa.Boolean(), nullable=False),
    sa.Column('created_at', app.db.types.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.db.types.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['posting_id'], ['job_postings.id'], name=op.f('fk_job_feed_items_posting_id_job_postings'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_job_feed_items_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_feed_items')),
    sa.UniqueConstraint('user_id', 'posting_id', name='uq_job_feed_items_user_posting')
    )
    with op.batch_alter_table('job_feed_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_feed_items_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_feed_items_is_read'), ['is_read'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_feed_items_is_saved'), ['is_saved'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_feed_items_posting_id'), ['posting_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_feed_items_received_at'), ['received_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_feed_items_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_job_feed_items_user_received', ['user_id', 'received_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_feed_items', schema=None) as batch_op:
        batch_op.drop_index('ix_job_feed_items_user_received')
        batch_op.drop_index(batch_op.f('ix_job_feed_items_user_id'))
        batch_op.drop_index(batch_op.f('ix_job_feed_items_received_at'))
        batch_op.drop_index(batch_op.f('ix_job_feed_items_posting_id'))
        batch_op.drop_index(batch_op.f('ix_job_feed_items_is_saved'))
        batch_op.drop_index(batch_op.f('ix_job_feed_items_is_read'))
        batch_op.drop_index(batch_op.f('ix_job_feed_items_created_at'))

    op.drop_table('job_feed_items')
    with op.batch_alter_table('job_postings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_postings_workplace_type'))
        batch_op.drop_index('ix_job_postings_workplace_posted')
        batch_op.drop_index(batch_op.f('ix_job_postings_source'))
        batch_op.drop_index(batch_op.f('ix_job_postings_fingerprint'))
        batch_op.drop_index(batch_op.f('ix_job_postings_created_at'))
        batch_op.drop_index(batch_op.f('ix_job_postings_company_name'))

    op.drop_table('job_postings')
    # ### end Alembic commands ###
