"""p04 accounts routing contacts projects activities

Revision ID: 5478cb4a2d81
Revises: f32eb050fead
Create Date: 2026-08-18 14:00:16.733023
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import app.db.types  # noqa: F401  # custom column types used by autogenerate
import app.db.types
import sqlalchemy as sa
revision: str = '5478cb4a2d81'
down_revision: str | None = 'f32eb050fead'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('technologies',
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=True),
    sa.Column('aliases', app.db.types.JSONType, nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', app.db.types.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.db.types.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_technologies'))
    )
    with op.batch_alter_table('technologies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_technologies_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_technologies_name'), ['name'], unique=True)

    op.create_table('accounts',
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('legal_name', sa.String(length=240), nullable=True),
    sa.Column('account_type', sa.String(length=48), nullable=False),
    sa.Column('relationship_status', sa.String(length=48), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('industry', sa.String(length=120), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('is_existing_customer', sa.Boolean(), nullable=False),
    sa.Column('is_existing_partner', sa.Boolean(), nullable=False),
    sa.Column('is_approved_vendor', sa.Boolean(), nullable=False),
    sa.Column('has_msa', sa.Boolean(), nullable=False),
    sa.Column('contract_outsourcing_friendly', sa.Boolean(), nullable=False),
    sa.Column('payment_terms_days', sa.Integer(), nullable=True),
    sa.Column('owner_id', app.db.types.GUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('tags', app.db.types.JSONType, nullable=True),
    sa.Column('created_at', app.db.types.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.db.types.UTCDateTime(), nullable=False),
    sa.Column('deleted_at', app.db.types.UTCDateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_accounts_owner_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_accounts')),
    sa.UniqueConstraint('name', 'country', name='account_name_country')
    )
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_accounts_account_type'), ['account_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_accounts_country'), ['country'], unique=False)
        batch_op.create_index(batch_op.f('ix_accounts_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_accounts_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_accounts_is_existing_customer'), ['is_existing_customer'], unique=False)
        batch_op.create_index(batch_op.f('ix_accounts_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_accounts_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_accounts_relationship_status'), ['relationship_status'], unique=False)
        batch_op.create_index('ix_accounts_type_status', ['account_type', 'relationship_status'], unique=False)

    op.create_table('account_relationships',
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('from_account_id', app.db.types.GUID(), nullable=False),
    sa.Column('to_account_id', app.db.types.GUID(), nullable=False),
    sa.Column('relation_type', sa.String(length=48), nullable=False),
    sa.Column('is_preferred_route', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', app.db.types.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.db.types.UTCDateTime(), nullable=False),
    sa.CheckConstraint('from_account_id <> to_account_id', name=op.f('ck_account_relationships_no_self_relationship')),
    sa.ForeignKeyConstraint(['from_account_id'], ['accounts.id'], name=op.f('fk_account_relationships_from_account_id_accounts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_account_id'], ['accounts.id'], name=op.f('fk_account_relationships_to_account_id_accounts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_account_relationships')),
    sa.UniqueConstraint('from_account_id', 'to_account_id', 'relation_type', name='account_relationship_unique')
    )
    with op.batch_alter_table('account_relationships', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_account_relationships_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_account_relationships_from_account_id'), ['from_account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_account_relationships_to_account_id'), ['to_account_id'], unique=False)

    op.create_table('contacts',
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('account_id', app.db.types.GUID(), nullable=False),
    sa.Column('full_name', sa.String(length=160), nullable=False),
    sa.Column('title', sa.String(length=140), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=48), nullable=True),
    sa.Column('linkedin_url', sa.String(length=255), nullable=True),
    sa.Column('is_decision_maker', sa.Boolean(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', app.db.types.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.db.types.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_contacts_account_id_accounts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contacts'))
    )
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.create_index('ix_contacts_account_decision', ['account_id', 'is_decision_maker'], unique=False)
        batch_op.create_index(batch_op.f('ix_contacts_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contacts_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_contacts_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_contacts_full_name'), ['full_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_contacts_is_decision_maker'), ['is_decision_maker'], unique=False)

    op.create_table('projects',
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('account_id', app.db.types.GUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=48), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=48), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('location', sa.String(length=160), nullable=True),
    sa.Column('prime_contractor_id', app.db.types.GUID(), nullable=True),
    sa.Column('owner_id', app.db.types.GUID(), nullable=True),
    sa.Column('created_at', app.db.types.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.db.types.UTCDateTime(), nullable=False),
    sa.Column('deleted_at', app.db.types.UTCDateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_projects_account_id_accounts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_projects_owner_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['prime_contractor_id'], ['accounts.id'], name=op.f('fk_projects_prime_contractor_id_accounts'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_projects'))
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projects_account_id'), ['account_id'], unique=False)
        batch_op.create_index('ix_projects_account_status', ['account_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_end_date'), ['end_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_prime_contractor_id'), ['prime_contractor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_status'), ['status'], unique=False)

    op.create_table('activities',
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('activity_type', sa.String(length=48), nullable=False),
    sa.Column('subject', sa.String(length=240), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('outcome', sa.String(length=240), nullable=True),
    sa.Column('occurred_at', app.db.types.UTCDateTime(), nullable=False),
    sa.Column('follow_up_at', app.db.types.UTCDateTime(), nullable=True),
    sa.Column('completed_at', app.db.types.UTCDateTime(), nullable=True),
    sa.Column('user_id', app.db.types.GUID(), nullable=True),
    sa.Column('account_id', app.db.types.GUID(), nullable=True),
    sa.Column('contact_id', app.db.types.GUID(), nullable=True),
    sa.Column('project_id', app.db.types.GUID(), nullable=True),
    sa.Column('created_at', app.db.types.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.db.types.UTCDateTime(), nullable=False),
    sa.CheckConstraint('account_id IS NOT NULL OR contact_id IS NOT NULL OR project_id IS NOT NULL', name=op.f('ck_activities_activity_has_a_subject')),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_activities_account_id_accounts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], name=op.f('fk_activities_contact_id_contacts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_activities_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_activities_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_activities'))
    )
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activities_account_id'), ['account_id'], unique=False)
        batch_op.create_index('ix_activities_account_time', ['account_id', 'occurred_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_activities_activity_type'), ['activity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_activities_contact_id'), ['contact_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_activities_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_activities_follow_up_at'), ['follow_up_at'], unique=False)
        batch_op.create_index('ix_activities_followup_open', ['follow_up_at', 'completed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_activities_occurred_at'), ['occurred_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_activities_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_activities_user_id'), ['user_id'], unique=False)

    op.create_table('project_technologies',
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('project_id', app.db.types.GUID(), nullable=False),
    sa.Column('technology_id', app.db.types.GUID(), nullable=False),
    sa.Column('created_at', app.db.types.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.db.types.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_project_technologies_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['technology_id'], ['technologies.id'], name=op.f('fk_project_technologies_technology_id_technologies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project_technologies')),
    sa.UniqueConstraint('project_id', 'technology_id', name='project_technology_unique')
    )
    with op.batch_alter_table('project_technologies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_technologies_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_technologies_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_technologies_technology_id'), ['technology_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_technologies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_technologies_technology_id'))
        batch_op.drop_index(batch_op.f('ix_project_technologies_project_id'))
        batch_op.drop_index(batch_op.f('ix_project_technologies_created_at'))

    op.drop_table('project_technologies')
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activities_user_id'))
        batch_op.drop_index(batch_op.f('ix_activities_project_id'))
        batch_op.drop_index(batch_op.f('ix_activities_occurred_at'))
        batch_op.drop_index('ix_activities_followup_open')
        batch_op.drop_index(batch_op.f('ix_activities_follow_up_at'))
        batch_op.drop_index(batch_op.f('ix_activities_created_at'))
        batch_op.drop_index(batch_op.f('ix_activities_contact_id'))
        batch_op.drop_index(batch_op.f('ix_activities_activity_type'))
        batch_op.drop_index('ix_activities_account_time')
        batch_op.drop_index(batch_op.f('ix_activities_account_id'))

    op.drop_table('activities')
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_status'))
        batch_op.drop_index(batch_op.f('ix_projects_prime_contractor_id'))
        batch_op.drop_index(batch_op.f('ix_projects_owner_id'))
        batch_op.drop_index(batch_op.f('ix_projects_name'))
        batch_op.drop_index(batch_op.f('ix_projects_end_date'))
        batch_op.drop_index(batch_op.f('ix_projects_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_projects_created_at'))
        batch_op.drop_index('ix_projects_account_status')
        batch_op.drop_index(batch_op.f('ix_projects_account_id'))

    op.drop_table('projects')
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contacts_is_decision_maker'))
        batch_op.drop_index(batch_op.f('ix_contacts_full_name'))
        batch_op.drop_index(batch_op.f('ix_contacts_email'))
        batch_op.drop_index(batch_op.f('ix_contacts_created_at'))
        batch_op.drop_index(batch_op.f('ix_contacts_account_id'))
        batch_op.drop_index('ix_contacts_account_decision')

    op.drop_table('contacts')
    with op.batch_alter_table('account_relationships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_account_relationships_to_account_id'))
        batch_op.drop_index(batch_op.f('ix_account_relationships_from_account_id'))
        batch_op.drop_index(batch_op.f('ix_account_relationships_created_at'))

    op.drop_table('account_relationships')
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_index('ix_accounts_type_status')
        batch_op.drop_index(batch_op.f('ix_accounts_relationship_status'))
        batch_op.drop_index(batch_op.f('ix_accounts_owner_id'))
        batch_op.drop_index(batch_op.f('ix_accounts_name'))
        batch_op.drop_index(batch_op.f('ix_accounts_is_existing_customer'))
        batch_op.drop_index(batch_op.f('ix_accounts_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_accounts_created_at'))
        batch_op.drop_index(batch_op.f('ix_accounts_country'))
        batch_op.drop_index(batch_op.f('ix_accounts_account_type'))

    op.drop_table('accounts')
    with op.batch_alter_table('technologies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_technologies_name'))
        batch_op.drop_index(batch_op.f('ix_technologies_created_at'))

    op.drop_table('technologies')
    # ### end Alembic commands ###
