"""p11 deployments and billing

Revision ID: 7c78e52b08ef
Revises: e590a69fe477
Create Date: 2026-08-19 15:45:31.512068
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import app.db.types  # noqa: F401  # custom column types used by autogenerate
import sqlalchemy as sa
revision: str = '7c78e52b08ef'
down_revision: str | None = 'e590a69fe477'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deployments',
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('resource_id', app.db.types.GUID(), nullable=False),
    sa.Column('account_id', app.db.types.GUID(), nullable=True),
    sa.Column('end_customer_id', app.db.types.GUID(), nullable=True),
    sa.Column('project_id', app.db.types.GUID(), nullable=True),
    sa.Column('requirement_id', app.db.types.GUID(), nullable=True),
    sa.Column('submission_id', app.db.types.GUID(), nullable=True),
    sa.Column('role_title', sa.String(length=160), nullable=False),
    sa.Column('location', sa.String(length=160), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('actual_end_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=48), nullable=False),
    sa.Column('bill_rate', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('bill_currency', sa.String(length=3), nullable=False),
    sa.Column('bill_unit', sa.String(length=16), nullable=False),
    sa.Column('cost_rate', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('cost_currency', sa.String(length=3), nullable=False),
    sa.Column('cost_unit', sa.String(length=16), nullable=False),
    sa.Column('visa_cost', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('insurance_cost', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('other_cost', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('working_days_per_month', sa.Integer(), nullable=False),
    sa.Column('hours_per_day', sa.Integer(), nullable=False),
    sa.Column('extension_of_deployment_id', app.db.types.GUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('end_reason', sa.Text(), nullable=True),
    sa.Column('created_by', app.db.types.GUID(), nullable=True),
    sa.Column('created_at', app.db.types.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.db.types.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_deployments_account_id_accounts'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_deployments_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['end_customer_id'], ['accounts.id'], name=op.f('fk_deployments_end_customer_id_accounts'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['extension_of_deployment_id'], ['deployments.id'], name=op.f('fk_deployments_extension_of_deployment_id_deployments'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_deployments_project_id_projects'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['requirement_id'], ['requirements.id'], name=op.f('fk_deployments_requirement_id_requirements'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], name=op.f('fk_deployments_resource_id_resources'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], name=op.f('fk_deployments_submission_id_submissions'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_deployments'))
    )
    with op.batch_alter_table('deployments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_deployments_account_id'), ['account_id'], unique=False)
        batch_op.create_index('ix_deployments_account_status', ['account_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_deployments_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_deployments_end_date'), ['end_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_deployments_extension_of_deployment_id'), ['extension_of_deployment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_deployments_requirement_id'), ['requirement_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_deployments_resource_id'), ['resource_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_deployments_start_date'), ['start_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_deployments_status'), ['status'], unique=False)
        batch_op.create_index('ix_deployments_status_end', ['status', 'end_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_deployments_submission_id'), ['submission_id'], unique=False)

    op.create_table('billing_records',
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('deployment_id', app.db.types.GUID(), nullable=False),
    sa.Column('period_year', sa.Integer(), nullable=False),
    sa.Column('period_month', sa.Integer(), nullable=False),
    sa.Column('revenue_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('cost_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('gross_profit', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('margin_percent', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(length=48), nullable=False),
    sa.Column('is_estimated', sa.Boolean(), nullable=False),
    sa.Column('billable_days', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('confirmed_by', app.db.types.GUID(), nullable=True),
    sa.Column('created_by', app.db.types.GUID(), nullable=True),
    sa.Column('created_at', app.db.types.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.db.types.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['confirmed_by'], ['users.id'], name=op.f('fk_billing_records_confirmed_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_billing_records_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['deployment_id'], ['deployments.id'], name=op.f('fk_billing_records_deployment_id_deployments'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_billing_records')),
    sa.UniqueConstraint('deployment_id', 'period_year', 'period_month', name='billing_period_unique')
    )
    with op.batch_alter_table('billing_records', schema=None) as batch_op:
        batch_op.create_index('ix_billing_period', ['period_year', 'period_month', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_billing_records_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_billing_records_deployment_id'), ['deployment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_billing_records_period_month'), ['period_month'], unique=False)
        batch_op.create_index(batch_op.f('ix_billing_records_period_year'), ['period_year'], unique=False)
        batch_op.create_index(batch_op.f('ix_billing_records_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('billing_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_billing_records_status'))
        batch_op.drop_index(batch_op.f('ix_billing_records_period_year'))
        batch_op.drop_index(batch_op.f('ix_billing_records_period_month'))
        batch_op.drop_index(batch_op.f('ix_billing_records_deployment_id'))
        batch_op.drop_index(batch_op.f('ix_billing_records_created_at'))
        batch_op.drop_index('ix_billing_period')

    op.drop_table('billing_records')
    with op.batch_alter_table('deployments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_deployments_submission_id'))
        batch_op.drop_index('ix_deployments_status_end')
        batch_op.drop_index(batch_op.f('ix_deployments_status'))
        batch_op.drop_index(batch_op.f('ix_deployments_start_date'))
        batch_op.drop_index(batch_op.f('ix_deployments_resource_id'))
        batch_op.drop_index(batch_op.f('ix_deployments_requirement_id'))
        batch_op.drop_index(batch_op.f('ix_deployments_extension_of_deployment_id'))
        batch_op.drop_index(batch_op.f('ix_deployments_end_date'))
        batch_op.drop_index(batch_op.f('ix_deployments_created_at'))
        batch_op.drop_index('ix_deployments_account_status')
        batch_op.drop_index(batch_op.f('ix_deployments_account_id'))

    op.drop_table('deployments')
    # ### end Alembic commands ###
