"""p09 opportunity scores

Revision ID: d8893c6f8e5d
Revises: 0b82cec227ef
Create Date: 2026-08-19 11:30:02.581804
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import app.db.types  # noqa: F401  # custom column types used by autogenerate
import app.db.types
import sqlalchemy as sa
revision: str = 'd8893c6f8e5d'
down_revision: str | None = '0b82cec227ef'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('opportunity_scores',
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('requirement_id', app.db.types.GUID(), nullable=False),
    sa.Column('opportunity_id', app.db.types.GUID(), nullable=True),
    sa.Column('talent_match_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('addressability_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('commercial_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('opportunity_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('band', sa.String(length=48), nullable=False),
    sa.Column('addressability_band', sa.String(length=48), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('supply_gate', sa.Float(), nullable=True),
    sa.Column('monthly_revenue', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('monthly_cost', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('gross_profit', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('margin_percent', sa.Float(), nullable=True),
    sa.Column('contract_value', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('total_profit', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('is_converted', sa.Boolean(), nullable=False),
    sa.Column('components', app.db.types.JSONType, nullable=True),
    sa.Column('factor_breakdown', app.db.types.JSONType, nullable=True),
    sa.Column('commercial_breakdown', app.db.types.JSONType, nullable=True),
    sa.Column('positives', app.db.types.JSONType, nullable=True),
    sa.Column('risks', app.db.types.JSONType, nullable=True),
    sa.Column('missing_information', app.db.types.JSONType, nullable=True),
    sa.Column('suppressors', app.db.types.JSONType, nullable=True),
    sa.Column('recommended_action', sa.String(length=255), nullable=True),
    sa.Column('narrative', sa.Text(), nullable=True),
    sa.Column('addressability_config_version', sa.Integer(), nullable=True),
    sa.Column('commercial_config_version', sa.Integer(), nullable=True),
    sa.Column('opportunity_config_version', sa.Integer(), nullable=True),
    sa.Column('match_config_version', sa.Integer(), nullable=True),
    sa.Column('engine_version', sa.String(length=16), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('computed_at', app.db.types.UTCDateTime(), nullable=False),
    sa.Column('computed_by', app.db.types.GUID(), nullable=True),
    sa.Column('created_at', app.db.types.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.db.types.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['computed_by'], ['users.id'], name=op.f('fk_opportunity_scores_computed_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['requirement_id'], ['requirements.id'], name=op.f('fk_opportunity_scores_requirement_id_requirements'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_opportunity_scores'))
    )
    with op.batch_alter_table('opportunity_scores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_opportunity_scores_addressability_band'), ['addressability_band'], unique=False)
        batch_op.create_index(batch_op.f('ix_opportunity_scores_band'), ['band'], unique=False)
        batch_op.create_index(batch_op.f('ix_opportunity_scores_computed_at'), ['computed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_opportunity_scores_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_opportunity_scores_current', ['requirement_id', 'is_current'], unique=False)
        batch_op.create_index('ix_opportunity_scores_history', ['requirement_id', 'computed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_opportunity_scores_is_current'), ['is_current'], unique=False)
        batch_op.create_index(batch_op.f('ix_opportunity_scores_opportunity_id'), ['opportunity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_opportunity_scores_opportunity_score'), ['opportunity_score'], unique=False)
        batch_op.create_index('ix_opportunity_scores_rank', ['is_current', 'opportunity_score'], unique=False)
        batch_op.create_index(batch_op.f('ix_opportunity_scores_requirement_id'), ['requirement_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('opportunity_scores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_opportunity_scores_requirement_id'))
        batch_op.drop_index('ix_opportunity_scores_rank')
        batch_op.drop_index(batch_op.f('ix_opportunity_scores_opportunity_score'))
        batch_op.drop_index(batch_op.f('ix_opportunity_scores_opportunity_id'))
        batch_op.drop_index(batch_op.f('ix_opportunity_scores_is_current'))
        batch_op.drop_index('ix_opportunity_scores_history')
        batch_op.drop_index('ix_opportunity_scores_current')
        batch_op.drop_index(batch_op.f('ix_opportunity_scores_created_at'))
        batch_op.drop_index(batch_op.f('ix_opportunity_scores_computed_at'))
        batch_op.drop_index(batch_op.f('ix_opportunity_scores_band'))
        batch_op.drop_index(batch_op.f('ix_opportunity_scores_addressability_band'))

    op.drop_table('opportunity_scores')
    # ### end Alembic commands ###
