"""p07 matching and scoring configuration

Revision ID: d898443c3fd4
Revises: 30f9fc902d8e
Create Date: 2026-08-18 16:47:51.327407
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import app.db.types  # noqa: F401  # custom column types used by autogenerate
import app.db.types
import sqlalchemy as sa
revision: str = 'd898443c3fd4'
down_revision: str | None = '30f9fc902d8e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scoring_configurations',
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('kind', sa.String(length=48), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('payload', app.db.types.JSONType, nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', app.db.types.GUID(), nullable=True),
    sa.Column('created_at', app.db.types.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.db.types.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_scoring_configurations_created_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scoring_configurations')),
    sa.UniqueConstraint('kind', 'version', name='scoring_configuration_version')
    )
    with op.batch_alter_table('scoring_configurations', schema=None) as batch_op:
        batch_op.create_index('ix_scoring_configurations_active', ['kind', 'is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_scoring_configurations_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_scoring_configurations_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_scoring_configurations_kind'), ['kind'], unique=False)

    op.create_table('matches',
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('requirement_id', app.db.types.GUID(), nullable=False),
    sa.Column('resource_id', app.db.types.GUID(), nullable=False),
    sa.Column('direction', sa.String(length=48), nullable=False),
    sa.Column('overall_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('band', sa.String(length=48), nullable=False),
    sa.Column('skill_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('experience_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('technology_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('availability_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('location_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('cost_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('commercial_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('semantic_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('components', app.db.types.JSONType, nullable=True),
    sa.Column('gaps', app.db.types.JSONType, nullable=True),
    sa.Column('reasons', app.db.types.JSONType, nullable=True),
    sa.Column('warnings', app.db.types.JSONType, nullable=True),
    sa.Column('missing_information', app.db.types.JSONType, nullable=True),
    sa.Column('narrative', sa.Text(), nullable=True),
    sa.Column('weights_version', sa.Integer(), nullable=True),
    sa.Column('engine_version', sa.String(length=16), nullable=False),
    sa.Column('computed_at', app.db.types.UTCDateTime(), nullable=False),
    sa.Column('computed_by', app.db.types.GUID(), nullable=True),
    sa.Column('created_at', app.db.types.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.db.types.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['computed_by'], ['users.id'], name=op.f('fk_matches_computed_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['requirement_id'], ['requirements.id'], name=op.f('fk_matches_requirement_id_requirements'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], name=op.f('fk_matches_resource_id_resources'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_matches')),
    sa.UniqueConstraint('requirement_id', 'resource_id', 'direction', name='match_unique')
    )
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_matches_band'), ['band'], unique=False)
        batch_op.create_index(batch_op.f('ix_matches_computed_at'), ['computed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_matches_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_matches_direction'), ['direction'], unique=False)
        batch_op.create_index(batch_op.f('ix_matches_overall_score'), ['overall_score'], unique=False)
        batch_op.create_index(batch_op.f('ix_matches_requirement_id'), ['requirement_id'], unique=False)
        batch_op.create_index('ix_matches_requirement_rank', ['requirement_id', 'overall_score'], unique=False)
        batch_op.create_index(batch_op.f('ix_matches_resource_id'), ['resource_id'], unique=False)
        batch_op.create_index('ix_matches_resource_rank', ['resource_id', 'overall_score'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.drop_index('ix_matches_resource_rank')
        batch_op.drop_index(batch_op.f('ix_matches_resource_id'))
        batch_op.drop_index('ix_matches_requirement_rank')
        batch_op.drop_index(batch_op.f('ix_matches_requirement_id'))
        batch_op.drop_index(batch_op.f('ix_matches_overall_score'))
        batch_op.drop_index(batch_op.f('ix_matches_direction'))
        batch_op.drop_index(batch_op.f('ix_matches_created_at'))
        batch_op.drop_index(batch_op.f('ix_matches_computed_at'))
        batch_op.drop_index(batch_op.f('ix_matches_band'))

    op.drop_table('matches')
    with op.batch_alter_table('scoring_configurations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scoring_configurations_kind'))
        batch_op.drop_index(batch_op.f('ix_scoring_configurations_is_active'))
        batch_op.drop_index(batch_op.f('ix_scoring_configurations_created_at'))
        batch_op.drop_index('ix_scoring_configurations_active')

    op.drop_table('scoring_configurations')
    # ### end Alembic commands ###
