"""p10 sales pipeline

Revision ID: e590a69fe477
Revises: d8893c6f8e5d
Create Date: 2026-08-19 12:17:20.989186
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import app.db.types  # noqa: F401  # custom column types used by autogenerate
import app.db.types
import sqlalchemy as sa
revision: str = 'e590a69fe477'
down_revision: str | None = 'd8893c6f8e5d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('opportunities',
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('requirement_id', app.db.types.GUID(), nullable=False),
    sa.Column('account_id', app.db.types.GUID(), nullable=True),
    sa.Column('route_account_id', app.db.types.GUID(), nullable=True),
    sa.Column('stage', sa.String(length=48), nullable=False),
    sa.Column('sales_owner_id', app.db.types.GUID(), nullable=True),
    sa.Column('resourcing_owner_id', app.db.types.GUID(), nullable=True),
    sa.Column('next_action', sa.String(length=255), nullable=True),
    sa.Column('next_action_due_at', app.db.types.UTCDateTime(), nullable=True),
    sa.Column('probability_percent', sa.Integer(), nullable=True),
    sa.Column('expected_monthly_revenue', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('expected_margin_percent', sa.Float(), nullable=True),
    sa.Column('contract_value', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('decision', sa.String(length=48), nullable=True),
    sa.Column('decision_reason', sa.Text(), nullable=True),
    sa.Column('decided_by', app.db.types.GUID(), nullable=True),
    sa.Column('decided_at', app.db.types.UTCDateTime(), nullable=True),
    sa.Column('closed_reason', sa.Text(), nullable=True),
    sa.Column('closed_at', app.db.types.UTCDateTime(), nullable=True),
    sa.Column('created_at', app.db.types.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.db.types.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_opportunities_account_id_accounts'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['decided_by'], ['users.id'], name=op.f('fk_opportunities_decided_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['requirement_id'], ['requirements.id'], name=op.f('fk_opportunities_requirement_id_requirements'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resourcing_owner_id'], ['users.id'], name=op.f('fk_opportunities_resourcing_owner_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['route_account_id'], ['accounts.id'], name=op.f('fk_opportunities_route_account_id_accounts'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sales_owner_id'], ['users.id'], name=op.f('fk_opportunities_sales_owner_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_opportunities')),
    sa.UniqueConstraint('requirement_id', name=op.f('uq_opportunities_requirement_id'))
    )
    with op.batch_alter_table('opportunities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_opportunities_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_opportunities_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_opportunities_decision'), ['decision'], unique=False)
        batch_op.create_index('ix_opportunities_due', ['next_action_due_at', 'stage'], unique=False)
        batch_op.create_index(batch_op.f('ix_opportunities_next_action_due_at'), ['next_action_due_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_opportunities_resourcing_owner_id'), ['resourcing_owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_opportunities_sales_owner_id'), ['sales_owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_opportunities_stage'), ['stage'], unique=False)
        batch_op.create_index('ix_opportunities_stage_owner', ['stage', 'sales_owner_id'], unique=False)

    op.create_table('opportunity_stage_history',
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('opportunity_id', app.db.types.GUID(), nullable=False),
    sa.Column('from_stage', sa.String(length=48), nullable=True),
    sa.Column('to_stage', sa.String(length=48), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('user_id', app.db.types.GUID(), nullable=True),
    sa.Column('created_at', app.db.types.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.db.types.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], name=op.f('fk_opportunity_stage_history_opportunity_id_opportunities'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_opportunity_stage_history_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_opportunity_stage_history'))
    )
    with op.batch_alter_table('opportunity_stage_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_opportunity_stage_history_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_opportunity_stage_history_opportunity_id'), ['opportunity_id'], unique=False)

    op.create_table('submissions',
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('opportunity_id', app.db.types.GUID(), nullable=True),
    sa.Column('requirement_id', app.db.types.GUID(), nullable=False),
    sa.Column('resource_id', app.db.types.GUID(), nullable=False),
    sa.Column('match_id', app.db.types.GUID(), nullable=True),
    sa.Column('status', sa.String(length=48), nullable=False),
    sa.Column('submitted_by', app.db.types.GUID(), nullable=True),
    sa.Column('submitted_at', app.db.types.UTCDateTime(), nullable=True),
    sa.Column('proposed_bill_rate', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('proposed_bill_currency', sa.String(length=3), nullable=True),
    sa.Column('proposed_bill_unit', sa.String(length=16), nullable=True),
    sa.Column('cv_document_id', app.db.types.GUID(), nullable=True),
    sa.Column('client_feedback', sa.Text(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('duplicate_of_submission_id', app.db.types.GUID(), nullable=True),
    sa.Column('blocks_resubmission', sa.Boolean(), nullable=True),
    sa.Column('created_at', app.db.types.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.db.types.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cv_document_id'], ['documents.id'], name=op.f('fk_submissions_cv_document_id_documents'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['duplicate_of_submission_id'], ['submissions.id'], name=op.f('fk_submissions_duplicate_of_submission_id_submissions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], name=op.f('fk_submissions_match_id_matches'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], name=op.f('fk_submissions_opportunity_id_opportunities'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requirement_id'], ['requirements.id'], name=op.f('fk_submissions_requirement_id_requirements'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], name=op.f('fk_submissions_resource_id_resources'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.id'], name=op.f('fk_submissions_submitted_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_submissions')),
    sa.UniqueConstraint('requirement_id', 'resource_id', 'blocks_resubmission', name='submission_active_unique')
    )
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_submissions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_submissions_opportunity_id'), ['opportunity_id'], unique=False)
        batch_op.create_index('ix_submissions_pair', ['requirement_id', 'resource_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_submissions_requirement_id'), ['requirement_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_submissions_resource_id'), ['resource_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_submissions_status'), ['status'], unique=False)
        batch_op.create_index('ix_submissions_status_submitted', ['status', 'submitted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_submissions_submitted_at'), ['submitted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_submissions_submitted_by'), ['submitted_by'], unique=False)

    op.create_table('communications',
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('direction', sa.String(length=48), nullable=False),
    sa.Column('channel', sa.String(length=48), nullable=False),
    sa.Column('subject', sa.String(length=240), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('to_addresses', app.db.types.JSONType, nullable=True),
    sa.Column('cc_addresses', app.db.types.JSONType, nullable=True),
    sa.Column('status', sa.String(length=48), nullable=False),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.Column('sent_at', app.db.types.UTCDateTime(), nullable=True),
    sa.Column('opportunity_id', app.db.types.GUID(), nullable=True),
    sa.Column('submission_id', app.db.types.GUID(), nullable=True),
    sa.Column('contact_id', app.db.types.GUID(), nullable=True),
    sa.Column('resource_id', app.db.types.GUID(), nullable=True),
    sa.Column('user_id', app.db.types.GUID(), nullable=True),
    sa.Column('created_at', app.db.types.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.db.types.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], name=op.f('fk_communications_contact_id_contacts'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], name=op.f('fk_communications_opportunity_id_opportunities'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], name=op.f('fk_communications_resource_id_resources'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], name=op.f('fk_communications_submission_id_submissions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_communications_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_communications'))
    )
    with op.batch_alter_table('communications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_communications_channel'), ['channel'], unique=False)
        batch_op.create_index(batch_op.f('ix_communications_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_communications_opportunity_id'), ['opportunity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_communications_resource_id'), ['resource_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_communications_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_communications_submission_id'), ['submission_id'], unique=False)
        batch_op.create_index('ix_communications_timeline', ['opportunity_id', 'created_at'], unique=False)

    op.create_table('interviews',
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('submission_id', app.db.types.GUID(), nullable=False),
    sa.Column('scheduled_at', app.db.types.UTCDateTime(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('mode', sa.String(length=48), nullable=False),
    sa.Column('interviewer_name', sa.String(length=160), nullable=True),
    sa.Column('interviewer_contact_id', app.db.types.GUID(), nullable=True),
    sa.Column('location_or_link', sa.String(length=500), nullable=True),
    sa.Column('round_number', sa.Integer(), nullable=False),
    sa.Column('outcome', sa.String(length=48), nullable=False),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('reminder_sent_at', app.db.types.UTCDateTime(), nullable=True),
    sa.Column('created_by', app.db.types.GUID(), nullable=True),
    sa.Column('created_at', app.db.types.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.db.types.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_interviews_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['interviewer_contact_id'], ['contacts.id'], name=op.f('fk_interviews_interviewer_contact_id_contacts'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], name=op.f('fk_interviews_submission_id_submissions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_interviews')),
    sa.UniqueConstraint('submission_id', 'round_number', name='interview_round_unique')
    )
    with op.batch_alter_table('interviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_interviews_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_interviews_outcome'), ['outcome'], unique=False)
        batch_op.create_index(batch_op.f('ix_interviews_scheduled_at'), ['scheduled_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_interviews_submission_id'), ['submission_id'], unique=False)
        batch_op.create_index('ix_interviews_upcoming', ['scheduled_at', 'outcome'], unique=False)

    op.create_table('submission_history',
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('submission_id', app.db.types.GUID(), nullable=False),
    sa.Column('from_status', sa.String(length=48), nullable=True),
    sa.Column('to_status', sa.String(length=48), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('user_id', app.db.types.GUID(), nullable=True),
    sa.Column('created_at', app.db.types.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.db.types.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], name=op.f('fk_submission_history_submission_id_submissions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_submission_history_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_submission_history'))
    )
    with op.batch_alter_table('submission_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_submission_history_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_submission_history_submission_id'), ['submission_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submission_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_submission_history_submission_id'))
        batch_op.drop_index(batch_op.f('ix_submission_history_created_at'))

    op.drop_table('submission_history')
    with op.batch_alter_table('interviews', schema=None) as batch_op:
        batch_op.drop_index('ix_interviews_upcoming')
        batch_op.drop_index(batch_op.f('ix_interviews_submission_id'))
        batch_op.drop_index(batch_op.f('ix_interviews_scheduled_at'))
        batch_op.drop_index(batch_op.f('ix_interviews_outcome'))
        batch_op.drop_index(batch_op.f('ix_interviews_created_at'))

    op.drop_table('interviews')
    with op.batch_alter_table('communications', schema=None) as batch_op:
        batch_op.drop_index('ix_communications_timeline')
        batch_op.drop_index(batch_op.f('ix_communications_submission_id'))
        batch_op.drop_index(batch_op.f('ix_communications_status'))
        batch_op.drop_index(batch_op.f('ix_communications_resource_id'))
        batch_op.drop_index(batch_op.f('ix_communications_opportunity_id'))
        batch_op.drop_index(batch_op.f('ix_communications_created_at'))
        batch_op.drop_index(batch_op.f('ix_communications_channel'))

    op.drop_table('communications')
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_submissions_submitted_by'))
        batch_op.drop_index(batch_op.f('ix_submissions_submitted_at'))
        batch_op.drop_index('ix_submissions_status_submitted')
        batch_op.drop_index(batch_op.f('ix_submissions_status'))
        batch_op.drop_index(batch_op.f('ix_submissions_resource_id'))
        batch_op.drop_index(batch_op.f('ix_submissions_requirement_id'))
        batch_op.drop_index('ix_submissions_pair')
        batch_op.drop_index(batch_op.f('ix_submissions_opportunity_id'))
        batch_op.drop_index(batch_op.f('ix_submissions_created_at'))

    op.drop_table('submissions')
    with op.batch_alter_table('opportunity_stage_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_opportunity_stage_history_opportunity_id'))
        batch_op.drop_index(batch_op.f('ix_opportunity_stage_history_created_at'))

    op.drop_table('opportunity_stage_history')
    with op.batch_alter_table('opportunities', schema=None) as batch_op:
        batch_op.drop_index('ix_opportunities_stage_owner')
        batch_op.drop_index(batch_op.f('ix_opportunities_stage'))
        batch_op.drop_index(batch_op.f('ix_opportunities_sales_owner_id'))
        batch_op.drop_index(batch_op.f('ix_opportunities_resourcing_owner_id'))
        batch_op.drop_index(batch_op.f('ix_opportunities_next_action_due_at'))
        batch_op.drop_index('ix_opportunities_due')
        batch_op.drop_index(batch_op.f('ix_opportunities_decision'))
        batch_op.drop_index(batch_op.f('ix_opportunities_created_at'))
        batch_op.drop_index(batch_op.f('ix_opportunities_account_id'))

    op.drop_table('opportunities')
    # ### end Alembic commands ###
