"""p05 requirements skills and jd parsing

Revision ID: fb9ad09a68d9
Revises: 5478cb4a2d81
Create Date: 2026-08-18 14:46:02.449934
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import app.db.types  # noqa: F401  # custom column types used by autogenerate
import app.db.types
import sqlalchemy as sa
revision: str = 'fb9ad09a68d9'
down_revision: str | None = '5478cb4a2d81'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skills',
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('normalized', sa.String(length=120), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=True),
    sa.Column('aliases', app.db.types.JSONType, nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('needs_review', sa.Boolean(), nullable=False),
    sa.Column('created_at', app.db.types.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.db.types.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_skills'))
    )
    with op.batch_alter_table('skills', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_skills_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_skills_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_skills_name'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('ix_skills_needs_review'), ['needs_review'], unique=False)
        batch_op.create_index(batch_op.f('ix_skills_normalized'), ['normalized'], unique=True)

    op.create_table('requirements',
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('title', sa.String(length=240), nullable=False),
    sa.Column('role', sa.String(length=160), nullable=True),
    sa.Column('description_raw', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=160), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('work_mode', sa.String(length=48), nullable=True),
    sa.Column('contract_type', sa.String(length=48), nullable=True),
    sa.Column('experience_min_years', sa.Integer(), nullable=True),
    sa.Column('experience_max_years', sa.Integer(), nullable=True),
    sa.Column('duration_months', sa.Integer(), nullable=True),
    sa.Column('positions', sa.Integer(), nullable=False),
    sa.Column('start_by_date', sa.Date(), nullable=True),
    sa.Column('availability_requirement', sa.String(length=160), nullable=True),
    sa.Column('rate_min', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('rate_max', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('rate_currency', sa.String(length=3), nullable=True),
    sa.Column('rate_unit', sa.String(length=48), nullable=True),
    sa.Column('account_id', app.db.types.GUID(), nullable=True),
    sa.Column('end_customer_id', app.db.types.GUID(), nullable=True),
    sa.Column('route_account_id', app.db.types.GUID(), nullable=True),
    sa.Column('project_id', app.db.types.GUID(), nullable=True),
    sa.Column('priority_source', sa.String(length=48), nullable=False),
    sa.Column('source', sa.String(length=48), nullable=False),
    sa.Column('source_detail', sa.String(length=255), nullable=True),
    sa.Column('external_reference', sa.String(length=120), nullable=True),
    sa.Column('status', sa.String(length=48), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('owner_id', app.db.types.GUID(), nullable=True),
    sa.Column('response_deadline_at', app.db.types.UTCDateTime(), nullable=True),
    sa.Column('review_status', sa.String(length=48), nullable=False),
    sa.Column('parsed_payload', app.db.types.JSONType, nullable=True),
    sa.Column('parse_confidence', sa.Float(), nullable=True),
    sa.Column('parse_model', sa.String(length=80), nullable=True),
    sa.Column('parsed_at', app.db.types.UTCDateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', app.db.types.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.db.types.UTCDateTime(), nullable=False),
    sa.Column('deleted_at', app.db.types.UTCDateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_requirements_account_id_accounts'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['end_customer_id'], ['accounts.id'], name=op.f('fk_requirements_end_customer_id_accounts'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_requirements_owner_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_requirements_project_id_projects'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['route_account_id'], ['accounts.id'], name=op.f('fk_requirements_route_account_id_accounts'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_requirements'))
    )
    with op.batch_alter_table('requirements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_requirements_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_requirements_contract_type'), ['contract_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_requirements_country'), ['country'], unique=False)
        batch_op.create_index(batch_op.f('ix_requirements_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_requirements_deadline_open', ['response_deadline_at', 'is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_requirements_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_requirements_end_customer_id'), ['end_customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_requirements_external_reference'), ['external_reference'], unique=False)
        batch_op.create_index(batch_op.f('ix_requirements_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_requirements_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index('ix_requirements_owner_status', ['owner_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_requirements_priority_source'), ['priority_source'], unique=False)
        batch_op.create_index(batch_op.f('ix_requirements_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_requirements_response_deadline_at'), ['response_deadline_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_requirements_review_status'), ['review_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_requirements_role'), ['role'], unique=False)
        batch_op.create_index(batch_op.f('ix_requirements_route_account_id'), ['route_account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_requirements_status'), ['status'], unique=False)
        batch_op.create_index('ix_requirements_status_active', ['status', 'is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_requirements_title'), ['title'], unique=False)

    op.create_table('requirement_skills',
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('requirement_id', app.db.types.GUID(), nullable=False),
    sa.Column('skill_id', app.db.types.GUID(), nullable=False),
    sa.Column('importance', sa.String(length=48), nullable=False),
    sa.Column('min_years', sa.Integer(), nullable=True),
    sa.Column('created_at', app.db.types.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.db.types.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['requirement_id'], ['requirements.id'], name=op.f('fk_requirement_skills_requirement_id_requirements'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], name=op.f('fk_requirement_skills_skill_id_skills'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_requirement_skills')),
    sa.UniqueConstraint('requirement_id', 'skill_id', name='requirement_skill_unique')
    )
    with op.batch_alter_table('requirement_skills', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_requirement_skills_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_requirement_skills_importance'), ['importance'], unique=False)
        batch_op.create_index(batch_op.f('ix_requirement_skills_requirement_id'), ['requirement_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_requirement_skills_skill_id'), ['skill_id'], unique=False)

    op.create_table('requirement_status_history',
    sa.Column('id', app.db.types.GUID(), nullable=False),
    sa.Column('requirement_id', app.db.types.GUID(), nullable=False),
    sa.Column('from_status', sa.String(length=48), nullable=True),
    sa.Column('to_status', sa.String(length=48), nullable=False),
    sa.Column('user_id', app.db.types.GUID(), nullable=True),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', app.db.types.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.db.types.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['requirement_id'], ['requirements.id'], name=op.f('fk_requirement_status_history_requirement_id_requirements'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_requirement_status_history_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_requirement_status_history'))
    )
    with op.batch_alter_table('requirement_status_history', schema=None) as batch_op:
        batch_op.create_index('ix_requirement_history_time', ['requirement_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_requirement_status_history_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_requirement_status_history_requirement_id'), ['requirement_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('requirement_status_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_requirement_status_history_requirement_id'))
        batch_op.drop_index(batch_op.f('ix_requirement_status_history_created_at'))
        batch_op.drop_index('ix_requirement_history_time')

    op.drop_table('requirement_status_history')
    with op.batch_alter_table('requirement_skills', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_requirement_skills_skill_id'))
        batch_op.drop_index(batch_op.f('ix_requirement_skills_requirement_id'))
        batch_op.drop_index(batch_op.f('ix_requirement_skills_importance'))
        batch_op.drop_index(batch_op.f('ix_requirement_skills_created_at'))

    op.drop_table('requirement_skills')
    with op.batch_alter_table('requirements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_requirements_title'))
        batch_op.drop_index('ix_requirements_status_active')
        batch_op.drop_index(batch_op.f('ix_requirements_status'))
        batch_op.drop_index(batch_op.f('ix_requirements_route_account_id'))
        batch_op.drop_index(batch_op.f('ix_requirements_role'))
        batch_op.drop_index(batch_op.f('ix_requirements_review_status'))
        batch_op.drop_index(batch_op.f('ix_requirements_response_deadline_at'))
        batch_op.drop_index(batch_op.f('ix_requirements_project_id'))
        batch_op.drop_index(batch_op.f('ix_requirements_priority_source'))
        batch_op.drop_index('ix_requirements_owner_status')
        batch_op.drop_index(batch_op.f('ix_requirements_owner_id'))
        batch_op.drop_index(batch_op.f('ix_requirements_is_active'))
        batch_op.drop_index(batch_op.f('ix_requirements_external_reference'))
        batch_op.drop_index(batch_op.f('ix_requirements_end_customer_id'))
        batch_op.drop_index(batch_op.f('ix_requirements_deleted_at'))
        batch_op.drop_index('ix_requirements_deadline_open')
        batch_op.drop_index(batch_op.f('ix_requirements_created_at'))
        batch_op.drop_index(batch_op.f('ix_requirements_country'))
        batch_op.drop_index(batch_op.f('ix_requirements_contract_type'))
        batch_op.drop_index(batch_op.f('ix_requirements_account_id'))

    op.drop_table('requirements')
    with op.batch_alter_table('skills', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_skills_normalized'))
        batch_op.drop_index(batch_op.f('ix_skills_needs_review'))
        batch_op.drop_index(batch_op.f('ix_skills_name'))
        batch_op.drop_index(batch_op.f('ix_skills_created_at'))
        batch_op.drop_index(batch_op.f('ix_skills_category'))

    op.drop_table('skills')
    # ### end Alembic commands ###
